# Generated by Django 4.2.4 on 2023-09-04 00:35

from django.db import models, migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        max_length=64, verbose_name="Task name to display"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of task to display"),
                ),
            ],
        ),
    ]
