# Generated by Django 4.2.4 on 2023-09-04 02:54

from django.db import migrations
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=tasks.models.CategoryField(default='default', verbose_name='Lowercase category naming'),
        ),
    ]
